name: chemml
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - anyio=4.12.1=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h9408147_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.1.0=pyhcf101f3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py311hee243d0_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=1.17.1=py311h3a79f62_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h7d85929_4
  - cpython=3.11.14=py311hd8ed1ab_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - debugpy=1.8.20=py311h8948835_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h50f4ffc_4
  - filelock=3.20.3=pyhd8ed1ab_0
  - fmt=12.1.0=h403dcb5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311ha9b3269_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py311hd340a2e_2
  - greenlet=3.3.1=py311h8325047_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libboost=1.86.0=h29978a0_2
  - libboost-python=1.86.0=py311h08cb3c8_5
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.8=hb4ce287_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.84.0=hdff4504_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - libntlm=1.8=h5505292_0
  - libopenblas=0.3.30=openmp_ha158390_4
  - libpng=1.6.54=h132b30e_0
  - libpq=18.1=h944245b_2
  - libprotobuf=6.31.1=h98f38fd_4
  - librdkit=2025.09.4=h26160e4_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.2=h1b79a29_0
  - libtiff=4.7.0=hfce79cd_1
  - libtorch=2.10.0=cpu_generic_hc627905_1
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=h4a912ad_0
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib=3.10.8=py311ha1ab1f8_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=7.5.3=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.4.1=py311had1e860_0
  - openjpeg=2.5.3=h889cd5d_1
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.1=hd24854e_1
  - optree=0.18.0=py311h5a5e7c7_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=py311hca03da5_1
  - pandas=3.0.0=py311h4a068b9_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.44=ha881caa_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=11.3.0=py311h1f9957d_3
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.2.2=py311he363849_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycairo=1.29.0=py311h6c5e815_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=11.0=py311hab620ed_0
  - pyobjc-framework-cocoa=11.0=py311hab620ed_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h89a136b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.10.0=cpu_generic_py311_h1662354_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - qhull=2020.2=h420ef59_5
  - rdkit=2025.09.4=py311h756a433_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=pyhcf101f3_0
  - reportlab=4.4.9=py311hc949640_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rlpycairo=0.4.0=pyh6c17108_0
  - rpds-py=0.30.0=py311h71babbd_0
  - scikit-learn=1.4.2=py311hbfb48bc_1
  - scipy=1.17.0=py311he9931d0_1
  - send2trash=2.1.0=pyh5552912_0
  - setuptools=80.10.1=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sqlalchemy=2.0.46=py311he363849_1
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - terminado=0.18.1=pyhc90fa1f_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py311h9408147_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=he532380_0
  - unicodedata2=17.0.0=py311h9408147_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.46.3=py311hca03da5_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - click==8.3.1
      - datasets==4.5.0
      - dill==0.4.0
      - evaluate==0.4.6
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - hf-xet==1.2.0
      - huggingface-hub==1.3.5
      - lightgbm==4.6.0
      - multidict==6.7.1
      - multiprocess==0.70.18
      - propcache==0.4.1
      - pyarrow==23.0.0
      - regex==2026.1.15
      - safetensors==0.7.0
      - shellingham==1.5.4
      - tokenizers==0.22.2
      - torch-geometric==2.7.0
      - tqdm==4.67.2
      - transformers==5.0.0
      - typer-slim==0.21.1
      - xgboost==3.1.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/anaconda3/envs/chemml
